config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    resources :movies, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director

  # BASIC PG_SEARCH MODEL SETUP
  searchkick
  include PgSearch

  pg_search_scope :search_by_title_and_syllabus,
    against: [ :title, :syllabus ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }


  # ASSOCIATION SCOPE

  pg_search_scope :global_search,
      against: [ :title, :syllabus ],
      associated_against: {
        director: [ :first_name, :last_name ]
      },
      using: {
        tsearch: { prefix: true }
      }


  # MULTISEARCH MODEL SETUP

  multisearchable against: [ :title, :syllabus ]

end

app/models/serie.rb
class Serie < ApplicationRecord
  include PgSearch
  multisearchable against: [ :title, :syllabus ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  # NOOB LEVEL BASIC - Will break when no query is passed.

  # def index
  #   @movies = Movie.where(title: params[:query])
  # end

  # # CODING POTWASHER - Won't break if no params are passed, but only finds exact matches.

  # def index
  #   if params[:query].present?
  #     @movies = Movie.where(title: params[:query])
  #   else
  #     @movies = Movie.all
  #   end
  # end

  # # GETTING THERE - ILIKE for case insensitivity and % for open ended matches.

  # def index
  #   if params[:query].present?
  #     @movies = Movie.where("title ILIKE ?", "%#{params[:query]}%")
  #   else
  #     @movies = Movie.all
  #   end
  # end

  # # MULTIPLE COLUMN SEARCH -

  # def index
  #   if params[:query].present?
  #     sql_query = "title ILIKE :query_key OR syllabus ILIKE :query_key"
  #     @movies = Movie.where(sql_query, query_key: "%#{params[:query]}%")
  #   else
  #     @movies = Movie.all
  #   end
  # end

  # ABOVE AND BELOW EMPHASISE WHICH VARIABLES AND KEYS ARE GOING WHERE

  # def index
  #   if params[:query].present?
  #     query = "title ILIKE :query OR syllabus ILIKE :query"
  #     @movies = Movie.where(query, query: "%#{params[:query]}%")
  #   else
  #     @movies = Movie.all
  #   end
  # end

  # ASSOCIATION SEARCH - Can search on the movie model and the associated director model

  # def index
  #   if params[:query].present?
  #     sql_query = " \
  #       movies.title ILIKE :query \
  #       OR movies.syllabus ILIKE :query \
  #       OR directors.first_name ILIKE :query \
  #       OR directors.last_name ILIKE :query \
  #     "
  #     @movies = Movie.joins(:director).where(sql_query, query: "%#{params[:query]}%")
  #   else
  #     @movies = Movie.all
  #   end
  # end

  #

  # SEARCH THAT FINDS WORD COMBOS IN THE WRONG ORDER - "superman batman" will now find "batman vs superman"

  # def index
  #   if params[:query].present?
  #     sql_query = " \
  #       movies.title @@ :query \
  #       OR movies.syllabus @@ :query \
  #       OR directors.first_name @@ :query \
  #       OR directors.last_name @@ :query \
  #     "
  #     @movies = Movie.joins(:director).where(sql_query, query: "%#{params[:query]}%")
  #   else
  #     @movies = Movie.all
  #   end
  # end

  # TIME TO GET SOMETHING MORE POWERFUL LET'S GO OVER TO THE MODEL AND PUT PGSEARCH IN

  # def index
  #   if params[:query].present?
  #     @movies = Movie.search_by_title_and_syllabus(params[:query])
  #   else
  #     @movies = Movie.all
  #   end
  # end

  # # ASSOCIATED PG SEARCH

  # def index
  #   if params[:query].present?
  #     @movies = Movie.global_search(params[:query])
  #   else
  #     @movies = Movie.all
  #   end
  # end

  # MULTISEARCH

  # def index
  #   if params[:query].present?
  #     @results = PgSearch.multisearch(params[:query])
  #   else
  #     @actv_results = [Movie.all, Serie.all].flatten
  #   end
  # end

  # ELASTICSEARCH

  # def index
  #   if params[:query].present?
  #     @movies = Movie.search(params[:query])
  #   else
  #     @movies = [Movie.all, Serie.all].flatten
  #   end
  # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/movies/index.html.erb
<%= form_tag movies_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a movie"
  %>
<% end %>
<% if @results %>
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div id="movies">
          <% @results.each do |movie| %>
            <h4><%= movie.searchable.title %></h4>
            <p><%= movie.searchable.syllabus %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% elsif @actv_results %>
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div id="movies">
          <% @actv_results.each do |movie| %>
            <h4><%= movie.title %></h4>
            <p><%= movie.syllabus %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% elsif @movies %>
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div id="movies">
          <% @movies.each do |movie| %>
            <h4><%= movie.title %></h4>
            <p><%= movie.syllabus %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>